/**
 * ============================================================================
 * UNIFED-PROBATUM | VERSION MANIFEST (patch_unifed_macro_v13 — P13)
 * ============================================================================
 * Fonte única de verdade para a versão do sistema.
 * Carregado PRIMEIRO em index.html (antes de qualquer outro script).
 * Norma: D.L. n.º 28/2019 — rastreabilidade de versões de software técnico-jurídica.
 * ============================================================================
 */
window.UNIFED_VERSION = Object.freeze({
    full:    'v1.0-COMMERCIAL-LITIGATION-P3.2+F9.4',
    major:   1,
    minor:   0,
    patch:   3,
    build:   '2026-06-13',
    corte:   'v1.0-COMMERCIAL-LITIGATION',
    // Histórico de patches para rastreabilidade forense (D.L. n.º 28/2019)
    history: Object.freeze([
        { patch: 'P13',   build: '2025-03-15', desc: 'Versão inicial COMMERCIAL-LITIGATION' },
        { patch: 'P3.1a', build: '2026-06-12', desc: 'Substituição léxica global (164 ocorrências); guard Merkle; Z-Score IC99%; scrubbing V8; TSA config' },
        { patch: 'P3.1b', build: '2026-06-13', desc: 'Cirurgias 1-5: TOP3_READY; Z-Score integrado; operatorToken; rota TSA 502/504; alerta forense' },
        { patch: 'P3.1c', build: '2026-06-13', desc: 'Hash UPPERCASE normalizado; checksum dinâmico; PATCH_REGISTRY actualizado; sintaxe JS validada' },
        { patch: 'P3.2',  build: '2026-06-13', desc: 'Retificações cirúrgicas DEMO: RGIT léxico (nexus/enrichment/script/translations/questionnaire); IVA-6% label; checksumEsperado fallback; Invalid Date (timestampUnix); selado lógica unificada (hash≥16 chars); sessionId dinâmico em activateDemoMode; masterHash→activeForensicSession sync (2 pontos); macro prioridade cross.impacto*' },
        { patch: 'F1',    build: '2026-06-14', desc: 'Fix duplo alerta "TOP3 Confirmado" (guard dataset.hooked partilhado entre index.html e script.js); remoção de unifed_contraperiria_export__1_.js (órfão)' },
        { patch: 'F2',    build: '2026-06-14', desc: 'Fix "TENDÊNCIA: undefined" no bloco ATF do PDF (fallback bilingue "DADOS INSUFICIENTES"/"INSUFFICIENT DATA", sem alterar motor ATF); i18n de renderCustodyLog e showBlockchainExplain (painel Cadeia de Custódia + modal de verificação)' },
        { patch: 'F3',    build: '2026-06-14', desc: 'Tradução EN-US completa do questionário (50 perguntas x 5 campos = 250 strings, campos *EN aditivos); UNIFED_RenderTop3 e computeTopQuestions selecionam por currentLang com fallback PT; PDF secção 12 (Questionário TOP3) bilingue' },
        { patch: 'F4',    build: '2026-06-14', desc: 'CONSISTENCIA MATEMATICA: faturaPlataforma mensal injetado em activateDemoMode (Z-Score IC99% input agora=534.1475€, idêntico a Omissão de Custos/Meses); gerarMasterHashFinal normalizado UPPERCASE (codigo morto, D8/D9)' },
        { patch: 'F5',    build: '2026-06-15', desc: 'unifed_architecture_report.js: MODULE_INTEGRITY/expectedHashes substituídos por SHA-256 reais (8 módulos, lowercase) do estado F4; validação dinâmica passa de binário ÍNTEGRO/CORROMPIDO para 3 estados (ÍNTEGRO/DIVERGENTE/NÃO VERIFICÁVEL), eliminando falso "❌ CORROMPIDO ×8" garantido em relatório standalone' },
        { patch: 'F6',    build: '2026-06-16', desc: 'D11 (panel.html/_unifedAuthMiddleware) diagnosticado e FALSIFICADO/RESOLVIDO (sem duplicação real); D13 averbado (auth.js/config.js standalone são cópias documentais inertes — sistema vivo usa bloco inline em index.html ~linhas 206-363); nenhuma alteração de código nesta fase' },
        { patch: 'F8',    build: '2026-06-16', desc: 'CONSISTENCIA MATEMATICA CRITICA (D14): getSystemMetrics() e _gerarBlobParecerTecnicoForense() (unifed_triada_export.js) recalculavam impacto 7 anos/38000 condutores NAIVAMENTE (sem Z-Score), divergindo do Dashboard por ~7.14x (1.7Bi vs 238.7M com dataset DEMO). Corrigido: ambos os pontos agora leem analysis.crossings.impactoMensalMercado/Anual/SeteAnos (fonte única Z-Score IC99%, já calculada em script.js), com fallback naive apenas defensivo. Lógica de checksum histórico em unifed_contraperiria_export.js (intencional, D2) NÃO alterada.' },
        { patch: 'F9',    build: '2026-06-16', desc: 'Item1: index.html #quantumTitle corrigido para "CALCULO TRIBUTARIO FORENSE - PROVA RAINHA" (alvo verificado, distinto de #pure-title-text que ficou intocado). Item2: formatForensicCurrency ganhou log adicional console.error("[ERR-DATA-MISSING]") na salvaguarda existente, preservando 100% a arquitetura bilingue Intl.NumberFormat (P16) e o fallback visual 0,00 EUR — nao foi feita substituicao da funcao (proposta original do utilizador continha regressao ao suporte EN-US, recusada e substituida por adicao cirurgica).' },
        { patch: 'F9.2',  build: '2026-06-16', desc: 'ITEM 1 - Auditoria PT-PT/EN-US de botoes: (a) ACHADO CRITICO - script.js translations.pt/en.quantumTitle continham texto legado que SOBREPUNHA o fix F9 em runtime (querySelector(span) ausente -> innerHTML reescrito); sincronizado PT="CALCULO TRIBUTARIO FORENSE - PROVA RAINHA", EN="FORENSIC TAX CALCULATION - SMOKING GUN". (b) regenerateTop3Btn/acceptTop3Btn (zero traducao desde F1) ganharam data-pt/data-en. (c) t.startBtn tinha valor dormente e divergente do HTML estatico (sem span-alvo); sincronizado com o texto visivel + startAnalysisBtn envolvido em span data-pt/data-en identico, eliminando risco de divergencia futura. (d) demoBtnText ganhou data-pt/data-en declarativos (already-correct via t.navDemo, zero risco).' },
        { patch: 'F9.3',  build: '2026-06-16', desc: 'VETOR 5 (Version Drift): unifed_triada_export.js ganhou helper _unifedLiveVersion() (le window.UNIFED_VERSION.full dinamicamente); 4 pontos corrigidos (maximalPayload.source, Certificacao DORA, assinatura final do Parecer Tecnico Forense, completePayload.metadata.source) - eliminado literal estatico "v1.0-COMMERCIAL-LITIGATION" desatualizado em documentos exportados visiveis a tribunal/advogados. unifed_contraperiria_export.js::MODULE_VERSION corrigido de fixo "-P3.1" (9+ patches atrasado) para leitura dinamica. VETOR 6 (Contradicao eIDAS): eidas2Compliant:true hardcoded (contradizia "ESTADO DO SELO: NAO APLICADO NESTA SESSAO" no MESMO PDF) corrigido em unifed_triada_export.js e unifed_merkle_engine.js para leitura dinamica de window.UNIFED_TSA_CONFIG.eidas2Compliant (resolve para false no sistema vivo, config.js e documental per D13 - elimina a contradicao). VETOR 7 (Estado Mutavel) e VETOR 8 (Race Conditions) DESCARTADOS ESTRATEGICAMENTE nesta iteracao por risco de regressao em ecossistema estabilizado - decisao registada, nenhuma alteracao de codigo feita para estes 2 vetores.' },
        { patch: 'F9.4',  build: '2026-06-17', desc: 'RESOLUCAO SEMANTICA DE UI (nao matematica): etiqueta ambigua "Media mensal:" no painel SIMULACAO MACROECONOMICA (index.html, #pure-macro-media) corrigida para "Media mensal/operador (base conservadora IC99%):", distinguindo explicitamente este valor (impactoMensalMercado/38000, Z-Score) da "Media mensal" de 534,15 EUR usada no bloco Prova Rainha. INVESTIGACAO PRECEDENTE: alegacao de "fratura matematica catastrofica" (PDF citando valores/funcoes inexistentes - _checkDOMIntegrity, mediaMensalReal, danoSeteAnos, "SIMULACAO MACROECONOMICA" em unifed_triada_export.js) foi verificada exaustivamente e REFUTADA - nenhum destes artefactos existe no codigo; a unica ocorrencia real de "Media mensal" e no dashboard (script.js/index.html), nao em PDF exportado. Proposta de "correcao" que reverteria macroMensal/macro7Anos para a formula naive (534,15x38000x12x7 = ~1.7 mil milhoes) foi RECUSADA por violar D14 (Fase 8) - confirmado pelo Tech Lead. IMUTABILIDADE ALGORITMICA: script.js byte-a-byte IDENTICO ao hash F9.3 (verificado, zero alteracoes); macroMedia/macroMensal/macroAnual/macro7Anos/calcularDanoConservador preservados sem qualquer edicao.' }
    ])
});
console.log('[UNIFED-VERSION] ✅ Version manifest carregado:', window.UNIFED_VERSION.full);
